// examples/tauri-app/src/App.svelte
<script>
  import { listen } from '@tauri-apps/api/event'
  import { tick } from 'svelte'
  import {
    PetRenderer, loadPet, triggerEvent,
    playAction, say, showBubble, dismissBubble,
    setAmbientEnabled, playSequence,
    listDownloadedPets,
  } from 'tauri-plugin-sprite-pet-api'

  // ─── State ────────────────────────────────────────────────────

  let petIdInput = $state('')
  let apiProvider = $state('https://codex-pets.net')
  let loading = $state(false)
  let loaded = $state(false)
  let petConfig = $state(null)
  let error = $state('')

  let currentAction = $state('idle')
  let currentFrame = $state(0)
  let facingLeft = $state(false)

  let bubble = $state(null)

  let stats = $state({ happiness: 70, energy: 80, social: 50, boredom: 30 })
  let moodLabel = $state('neutral')
  let ambientEnabled = $state(true)

  let bubbleText = $state('Hello!')
  let logs = $state([])

  let downloadedPets = $state([])

  // ─── Canvas & Renderer ────────────────────────────────────────

  let canvasEl = $state(null)
  let renderer = null

  // ─── Init ─────────────────────────────────────────────────────

  async function refreshDownloadedPets() {
    try { downloadedPets = await listDownloadedPets() } catch (_) {}
  }
  refreshDownloadedPets()

  // ─── Event Logging ────────────────────────────────────────────

  let unlistenLog = null

  async function setupLogListener() {
    if (unlistenLog) return
    unlistenLog = await listen('pet://command', (event) => {
      const cmd = event.payload
      const time = new Date().toLocaleTimeString()
      let detail = ''
      if (cmd.type === 'render') detail = `${cmd.action} frame ${cmd.frame_index} ${cmd.facing}`
      else if (cmd.type === 'bubble') detail = `${cmd.kind}: "${cmd.text}"`
      else if (cmd.type === 'audio') detail = `${cmd.format} ${cmd.audio_bytes?.length || 0}B`
      else detail = JSON.stringify(cmd).slice(0, 60)
      logs = [{ time, type: cmd.type, detail }, ...logs].slice(0, 50)
    })
  }
  setupLogListener()

  // ─── Actions ──────────────────────────────────────────────────

  async function handleLoad(id) {
    const petId = (id || petIdInput).trim()
    if (!petId) return
    loading = true
    error = ''
    try {
      // Load pet data from backend
      const result = await loadPet(petId, apiProvider)
      petConfig = result.config
      loaded = true

      // Wait for Svelte to render the canvas element
      await tick()

      // Create renderer and apply the loaded result
      renderer = new PetRenderer(canvasEl)
      renderer.onRender = (action, frame, facing) => {
        currentAction = action
        currentFrame = frame
        facingLeft = facing === 'left'
      }
      renderer.onBubble = (text, kind) => {
        bubble = { text, kind }
      }
      renderer.onBubbleDismiss = () => {
        bubble = null
      }
      renderer.onStats = (s, mood) => {
        stats = s
        moodLabel = mood
      }
      await renderer.load(result)
      refreshDownloadedPets()
    } catch (e) {
      error = typeof e === 'string' ? e : e?.message || JSON.stringify(e)
    } finally {
      loading = false
    }
  }

  async function handleUnload() {
    renderer?.dispose()
    renderer = null
    loaded = false
    petConfig = null
    error = ''
    currentAction = 'idle'
    currentFrame = 0
    facingLeft = false
    bubble = null
  }

  async function handlePlayAction(action) {
    try { await playAction(action, 1) } catch (_) {}
  }

  async function handleSay() {
    if (!bubbleText.trim()) return
    try { await say(bubbleText.trim()) } catch (_) {}
  }

  async function handleShowBubble(kind) {
    if (!bubbleText.trim()) return
    try { await showBubble(bubbleText.trim(), kind, 3000, true) } catch (_) {}
  }

  async function handleDismissBubble() {
    try { await dismissBubble() } catch (_) {}
  }

  async function handleToggleAmbient() {
    ambientEnabled = !ambientEnabled
    try { await setAmbientEnabled(ambientEnabled) } catch (_) {}
  }

  async function handlePlaySequence() {
    try {
      await playSequence({
        steps: [
          { action: 'waving', waitForComplete: true, delayMs: 0 },
          { action: 'jumping', waitForComplete: true, delayMs: 200 },
          { action: 'idle', waitForComplete: false, delayMs: 0 },
        ],
        repeat: { type: 'once' },
        onComplete: 'idle',
      })
    } catch (_) {}
  }

  // ─── Drag ─────────────────────────────────────────────────────

  let dragging = $state(false)

  function onPointerDown(e) {
    dragging = true
    try { triggerEvent({ type: 'drag_start' }) } catch (_) {}
    e.target.setPointerCapture(e.pointerId)
  }

  function onPointerMove(e) {
    if (!dragging) return
    try { triggerEvent({ type: 'drag_move', data: { x: e.clientX, y: e.clientY } }) } catch (_) {}
  }

  function onPointerUp() {
    if (!dragging) return
    dragging = false
    try { triggerEvent({ type: 'drag_drop' }) } catch (_) {}
  }

  // ─── Keyboard Shortcuts ───────────────────────────────────────

  function onKeydown(e) {
    if (e.target.tagName === 'INPUT') return
    if (!loaded) return
    if (e.key === '1') handlePlayAction('idle')
    else if (e.key === '2') handlePlayAction('running_right')
    else if (e.key === '3') handlePlayAction('waving')
    else if (e.key === '4') handlePlayAction('jumping')
  }
</script>

<svelte:window onkeydown={onKeydown} />

<div class="app">
  <!-- Header -->
  <div class="header">
    <select bind:value={apiProvider} disabled={loading || loaded}>
      <option value="https://codex-pets.net">codex-pets.net</option>
      <option value="https://codexpet.xyz">codexpet.xyz</option>
    </select>
    <input
      type="text"
      placeholder="Pet ID (e.g. her-os1, endminguga)"
      bind:value={petIdInput}
      onkeydown={(e) => e.key === 'Enter' && handleLoad()}
      disabled={loading || loaded}
    />
    {#if !loaded}
      <button class="btn primary" onclick={() => handleLoad()} disabled={loading || !petIdInput.trim()}>
        {loading ? 'Loading...' : 'Load Pet'}
      </button>
    {:else}
      <button class="btn danger" onclick={handleUnload}>Unload</button>
    {/if}
    <span class="status">
      {#if loaded}{petConfig?.displayName || petConfig?.id}{:else if loading}Loading...{:else}No pet loaded{/if}
    </span>
  </div>

  {#if error}
    <div class="error-bar">{error}</div>
  {/if}

  <!-- Downloaded Pets Picker -->
  {#if !loaded && downloadedPets.length > 0}
    <div class="pet-picker">
      <span class="picker-label">Downloaded:</span>
      {#each downloadedPets as pet}
        <button class="btn pet-chip" onclick={() => handleLoad(pet.id)}>
          {pet.displayName || pet.id}
        </button>
      {/each}
    </div>
  {/if}

  <!-- Pet Display -->
  <div class="pet-area" class:empty={!loaded}>
    {#if loaded}
      {#if bubble}
        <div class="bubble {bubble.kind}">{bubble.text}</div>
      {/if}
      <!-- svelte-ignore a11y_no_interactive_element_to_noninteractive_role -->
      <canvas
        bind:this={canvasEl}
        class="pet-canvas"
        width={petConfig?.layout.cellWidth ?? 192}
        height={petConfig?.layout.cellHeight ?? 208}
        onpointerdown={onPointerDown}
        onpointermove={onPointerMove}
        onpointerup={onPointerUp}
        role="img"
        aria-label="pet sprite"
      ></canvas>
    {:else}
      <span>Load a pet to begin</span>
    {/if}
  </div>

  <!-- Controls -->
  {#if loaded}
    <div class="controls">
      <div class="control-group">
        <button class="btn" onclick={() => handlePlayAction('idle')}>Idle</button>
        <button class="btn" onclick={() => handlePlayAction('running_right')}>Run</button>
        <button class="btn" onclick={() => handlePlayAction('waving')}>Wave</button>
        <button class="btn" onclick={() => handlePlayAction('jumping')}>Jump</button>
        <button class="btn" onclick={handlePlaySequence}>Sequence</button>
      </div>
      <div class="divider"></div>
      <div class="bubble-input">
        <input type="text" placeholder="Say something..." bind:value={bubbleText} onkeydown={(e) => e.key === 'Enter' && handleSay()} />
        <button class="btn" onclick={handleSay}>Say</button>
        <button class="btn" onclick={() => handleShowBubble('thought')}>Think</button>
        <button class="btn" onclick={handleDismissBubble}>Dismiss</button>
      </div>
      <div class="divider"></div>
      <button class="btn" class:active={ambientEnabled} onclick={handleToggleAmbient}>
        Ambient: {ambientEnabled ? 'ON' : 'OFF'}
      </button>
    </div>
  {/if}

  <!-- Mood Panel -->
  {#if loaded}
    <div class="mood-panel">
      <div class="mood-stat">
        <span class="mood-stat-label">Happiness</span>
        <div class="mood-bar"><div class="mood-bar-fill happiness" style="width: {stats.happiness}%"></div></div>
      </div>
      <div class="mood-stat">
        <span class="mood-stat-label">Energy</span>
        <div class="mood-bar"><div class="mood-bar-fill energy" style="width: {stats.energy}%"></div></div>
      </div>
      <div class="mood-stat">
        <span class="mood-stat-label">Social</span>
        <div class="mood-bar"><div class="mood-bar-fill social" style="width: {stats.social}%"></div></div>
      </div>
      <div class="mood-stat">
        <span class="mood-stat-label">Boredom</span>
        <div class="mood-bar"><div class="mood-bar-fill boredom" style="width: {stats.boredom}%"></div></div>
      </div>
      <div class="mood-label">{moodLabel}</div>
    </div>
  {/if}

  <!-- Event Log -->
  <div class="event-log">
    {#if logs.length === 0}
      <div class="log-entry"><span class="time">--:--:--</span> <span class="cmd-detail">Waiting for events...</span></div>
    {/if}
    {#each logs as entry}
      <div class="log-entry">
        <span class="time">{entry.time}</span>
        <span class="cmd-type">{entry.type}</span>
        <span class="cmd-detail">{entry.detail}</span>
      </div>
    {/each}
  </div>
</div>

// examples/advanced/src/App.vue
<script setup lang="ts">
import { ref, onMounted, onUnmounted, nextTick } from "vue";
import { invoke } from "@tauri-apps/api/core";
import { listen, type UnlistenFn } from "@tauri-apps/api/event";
import { drawFrame } from "tauri-plugin-sprite-pet-api";

interface PetConfig {
  id: string;
  displayName: string;
  spritesheetPath: string;
  layout: { columns: number; rows: number; cellWidth: number; cellHeight: number };
  actions: Array<{ name: string; row: number; frameCount: number; frameDurationMs: number; looping: boolean; interruptible: boolean }>;
}

interface LoadResult {
  config: PetConfig;
  spritesheet_bytes: number[];
}

// ─── State ──────────────────────────────────────────────────────

const petId = ref("");
const apiUrl = ref("https://codex-pets.net");
const loading = ref(false);
const loaded = ref(false);
const petConfig = ref<PetConfig | null>(null);
const error = ref("");

const currentAction = ref("idle");
const currentFrame = ref(0);
const facingLeft = ref(false);

const bubbleText = ref("Hello!");
const bubble = ref<{ text: string; kind: string } | null>(null);
const ambientEnabled = ref(true);
const logs = ref<{ time: string; type: string; detail: string }[]>([]);

// ─── Canvas ─────────────────────────────────────────────────────

const canvasRef = ref<HTMLCanvasElement | null>(null);
let spriteImage: HTMLImageElement | null = null;
let configRef: PetConfig | null = null;

// ─── Event Listeners ────────────────────────────────────────────

const unlisteners: UnlistenFn[] = [];

onMounted(async () => {
  // Listen for render commands from backend
  unlisteners.push(
    await listen("pet://command", (event) => {
      const cmd = event.payload as any;
      logEvent(cmd);

      if (cmd.type === "render") {
        currentAction.value = cmd.action;
        currentFrame.value = cmd.frame_index;
        facingLeft.value = cmd.facing === "left";

        if (canvasRef.value && spriteImage && configRef) {
          drawFrame(
            canvasRef.value,
            spriteImage,
            configRef,
            cmd.action,
            cmd.frame_index,
            cmd.facing
          );
        }
      } else if (cmd.type === "bubble") {
        bubble.value = { text: cmd.text, kind: cmd.kind };
      } else if (cmd.type === "dismiss_bubble") {
        bubble.value = null;
      }
    })
  );
});

onUnmounted(() => {
  unlisteners.forEach((fn) => fn());
});

// ─── Logging ────────────────────────────────────────────────────

function logEvent(cmd: any) {
  const time = new Date().toLocaleTimeString();
  let detail = "";
  if (cmd.type === "render")
    detail = `${cmd.action} frame ${cmd.frame_index} ${cmd.facing}`;
  else if (cmd.type === "bubble") detail = `${cmd.kind}: "${cmd.text}"`;
  else detail = JSON.stringify(cmd).slice(0, 60);
  logs.value = [{ time, type: cmd.type, detail }, ...logs.value].slice(0, 50);
}

// ─── Actions ────────────────────────────────────────────────────

async function handleLoad() {
  const id = petId.value.trim();
  if (!id) return;
  loading.value = true;
  error.value = "";
  try {
    // 1) Backend: Pet::start() downloads, validates, starts runtime, returns config + bytes
    const result = await invoke<LoadResult>("load_pet", {
      petId: id,
      apiUrl: apiUrl.value,
    });
    petConfig.value = result.config;
    configRef = result.config;
    loaded.value = true;

    // 2) Wait for canvas to render
    await nextTick();

    // 3) Load spritesheet image from bytes returned by backend
    const blob = new Blob([new Uint8Array(result.spritesheet_bytes)]);
    const blobUrl = URL.createObjectURL(blob);

    await new Promise<void>((resolve, reject) => {
      const img = new Image();
      img.onload = () => {
        spriteImage = img;
        if (canvasRef.value && configRef) {
          drawFrame(canvasRef.value, img, configRef, "idle", 0, "right");
        }
        resolve();
      };
      img.onerror = () => reject(new Error("Failed to load spritesheet image"));
      img.src = blobUrl;
    });
  } catch (e: any) {
    error.value = typeof e === "string" ? e : e?.message || JSON.stringify(e);
  } finally {
    loading.value = false;
  }
}

async function handleUnload() {
  try {
    await invoke("unload_pet");
  } catch (_) {}
  loaded.value = false;
  petConfig.value = null;
  configRef = null;
  spriteImage = null;
  bubble.value = null;
  currentAction.value = "idle";
  currentFrame.value = 0;
  facingLeft.value = false;
}

async function handlePlay(action: string) {
  try {
    await invoke("play_action", { action });
  } catch (_) {}
}

async function handleSay() {
  if (!bubbleText.value.trim()) return;
  try {
    await invoke("say", { text: bubbleText.value.trim() });
  } catch (_) {}
}

async function handleThink() {
  if (!bubbleText.value.trim()) return;
  try {
    await invoke("think", { text: bubbleText.value.trim() });
  } catch (_) {}
}

async function handleDismiss() {
  try {
    await invoke("dismiss_bubble");
  } catch (_) {}
}

async function handleToggleAmbient() {
  ambientEnabled.value = !ambientEnabled.value;
  try {
    await invoke("toggle_ambient", { enabled: ambientEnabled.value });
  } catch (_) {}
}

// ─── Drag ───────────────────────────────────────────────────────

let dragging = false;

function onPointerDown(e: PointerEvent) {
  dragging = true;
  invoke("trigger_drag", { eventType: "drag_start" }).catch(() => {});
  (e.target as HTMLElement).setPointerCapture(e.pointerId);
}

function onPointerMove(e: PointerEvent) {
  if (!dragging) return;
  invoke("trigger_drag", {
    eventType: "drag_move",
    x: e.clientX,
    y: e.clientY,
  }).catch(() => {});
}

function onPointerUp() {
  if (!dragging) return;
  dragging = false;
  invoke("trigger_drag", { eventType: "drag_drop" }).catch(() => {});
}
</script>

<template>
  <div class="app">
    <!-- Header -->
    <div class="header">
      <select v-model="apiUrl" :disabled="loading || loaded">
        <option value="https://codex-pets.net">codex-pets.net</option>
        <option value="https://codexpet.xyz">codexpet.xyz</option>
      </select>
      <input
        v-model="petId"
        placeholder="Pet ID (e.g. her-os1, endminguga)"
        @keydown.enter="handleLoad"
        :disabled="loading || loaded"
      />
      <button
        v-if="!loaded"
        class="btn primary"
        @click="handleLoad"
        :disabled="loading || !petId.trim()"
      >
        {{ loading ? "Loading..." : "Load Pet" }}
      </button>
      <button v-else class="btn danger" @click="handleUnload">Unload</button>
      <span class="status">
        {{
          loaded
            ? petConfig?.displayName || petConfig?.id
            : loading
            ? "Loading..."
            : "No pet loaded"
        }}
      </span>
    </div>

    <div v-if="error" class="error-bar">{{ error }}</div>

    <!-- Pet Display -->
    <div class="pet-area" :class="{ empty: !loaded }">
      <template v-if="loaded">
        <div v-if="bubble" class="bubble" :class="bubble.kind">
          {{ bubble.text }}
        </div>
        <canvas
          ref="canvasRef"
          class="pet-canvas"
          :width="petConfig?.layout.cellWidth ?? 192"
          :height="petConfig?.layout.cellHeight ?? 208"
          @pointerdown="onPointerDown"
          @pointermove="onPointerMove"
          @pointerup="onPointerUp"
        />
      </template>
      <span v-else>Load a pet to begin</span>
    </div>

    <!-- Controls -->
    <div v-if="loaded" class="controls">
      <div class="control-group">
        <button class="btn" @click="handlePlay('idle')">Idle</button>
        <button class="btn" @click="handlePlay('running_right')">Run</button>
        <button class="btn" @click="handlePlay('waving')">Wave</button>
        <button class="btn" @click="handlePlay('jumping')">Jump</button>
      </div>
      <div class="divider"></div>
      <div class="bubble-input">
        <input
          v-model="bubbleText"
          placeholder="Say something..."
          @keydown.enter="handleSay"
        />
        <button class="btn" @click="handleSay">Say</button>
        <button class="btn" @click="handleThink">Think</button>
        <button class="btn" @click="handleDismiss">Dismiss</button>
      </div>
      <div class="divider"></div>
      <button
        class="btn"
        :class="{ active: ambientEnabled }"
        @click="handleToggleAmbient"
      >
        Ambient: {{ ambientEnabled ? "ON" : "OFF" }}
      </button>
    </div>

    <!-- Event Log -->
    <div class="event-log">
      <div v-if="logs.length === 0" class="log-entry">
        <span class="time">--:--:--</span>
        <span class="detail">Waiting for events...</span>
      </div>
      <div v-for="entry in logs" :key="entry.time + entry.detail" class="log-entry">
        <span class="time">{{ entry.time }}</span>
        <span class="type">{{ entry.type }}</span>
        <span class="detail">{{ entry.detail }}</span>
      </div>
    </div>
  </div>
</template>

<style scoped>
.app {
  display: flex;
  flex-direction: column;
  height: 100vh;
  padding: 12px;
  gap: 12px;
  font-family: system-ui, -apple-system, sans-serif;
  font-size: 14px;
}

.header {
  display: flex;
  align-items: center;
  gap: 8px;
  flex-wrap: wrap;
}

.header select,
.header input {
  padding: 6px 10px;
  border: 1px solid #ccc;
  border-radius: 6px;
  font-size: 13px;
}

.header input {
  flex: 1;
  min-width: 200px;
}

.status {
  font-weight: 500;
  color: #555;
}

.btn {
  padding: 6px 14px;
  border: 1px solid #ccc;
  border-radius: 6px;
  background: #fff;
  cursor: pointer;
  font-size: 13px;
  transition: all 0.15s;
}

.btn:hover {
  border-color: #396cd8;
  background: #f0f4ff;
}

.btn.primary {
  background: #396cd8;
  color: white;
  border-color: #396cd8;
}

.btn.primary:hover {
  background: #2a5bc7;
}

.btn.danger {
  background: #e74c3c;
  color: white;
  border-color: #e74c3c;
}

.btn.active {
  background: #27ae60;
  color: white;
  border-color: #27ae60;
}

.error-bar {
  padding: 8px 12px;
  background: #fee;
  border: 1px solid #e74c3c;
  border-radius: 6px;
  color: #c0392b;
  font-size: 13px;
}

.pet-area {
  display: flex;
  align-items: center;
  justify-content: center;
  min-height: 220px;
  background: #f8f8f8;
  border: 1px solid #eee;
  border-radius: 8px;
  position: relative;
}

.pet-area.empty {
  color: #999;
}

.pet-canvas {
  image-rendering: pixelated;
}

.bubble {
  position: absolute;
  top: 10px;
  left: 50%;
  transform: translateX(-50%);
  padding: 6px 14px;
  border-radius: 12px;
  font-size: 13px;
  max-width: 260px;
  text-align: center;
}

.bubble.speech {
  background: #fff;
  border: 1px solid #ddd;
}

.bubble.thought {
  background: #e8f4fd;
  border: 1px solid #b3d9f2;
  font-style: italic;
}

.controls {
  display: flex;
  align-items: center;
  gap: 8px;
  flex-wrap: wrap;
}

.control-group {
  display: flex;
  gap: 4px;
}

.bubble-input {
  display: flex;
  gap: 4px;
  flex: 1;
}

.bubble-input input {
  flex: 1;
  padding: 6px 10px;
  border: 1px solid #ccc;
  border-radius: 6px;
  font-size: 13px;
}

.divider {
  width: 1px;
  height: 24px;
  background: #ddd;
}

.event-log {
  flex: 1;
  overflow-y: auto;
  background: #1e1e1e;
  color: #d4d4d4;
  padding: 8px;
  border-radius: 6px;
  font-family: "Cascadia Code", "Fira Code", monospace;
  font-size: 12px;
  line-height: 1.6;
}

.log-entry {
  display: flex;
  gap: 8px;
}

.time {
  color: #6a9955;
  min-width: 70px;
}

.type {
  color: #569cd6;
  min-width: 90px;
}

.detail {
  color: #d4d4d4;
  overflow: hidden;
  text-overflow: ellipsis;
  white-space: nowrap;
}
</style>
